# List of npm teams.
- description: '@:org members with read-only rights'
  member: :orgTeam/merger
  name: mergers
  permission: read-only
- description: '@:org members with read-write rights'
  member: :orgTeam/releaser
  name: releasers
  permission: read-write
